#!/bin/sh
mkdir build/Space\ Wars.app
mkdir build/Space\ Wars.app/Contents
mkdir build/Space\ Wars.app/Contents/MacOS
mkdir build/Space\ Wars.app/Contents/Resources
cp icon.png build/Space\ Wars.app/Contents/Resources/
cp build/Space\ Wars build/Space\ Wars.app/Contents/MacOS/
cp Info.plist build/Space\ Wars.app/Contents/
cd build/Space\ Wars.app/Contents/Resources
mkdir Icon.iconset
sips -z 16 16     icon.png --out Icon.iconset/icon_16x16.png
sips -z 32 32     icon.png --out Icon.iconset/icon_16x16@2x.png
sips -z 32 32     icon.png --out Icon.iconset/icon_32x32.png
sips -z 64 64     icon.png --out Icon.iconset/icon_32x32@2x.png
sips -z 128 128   icon.png --out Icon.iconset/icon_128x128.png
sips -z 256 256   icon.png --out Icon.iconset/icon_128x128@2x.png
sips -z 256 256   icon.png --out Icon.iconset/icon_256x256.png
sips -z 512 512   icon.png --out Icon.iconset/icon_256x256@2x.png
sips -z 512 512   icon.png --out Icon.iconset/icon_512x512.png
sips -z 1024 1024   icon.png --out Icon.iconset/icon_512x512@2x.png
sips -z 1024 1024   icon.png --out Icon.iconset/icon_1024x1024.png
cp icon.png Icon.iconset/icon_512x512@2x.png
iconutil -c icns Icon.iconset
rm -R Icon.iconset
rm icon.png