#ifndef CONFIG_H
#define CONFIG_H

#define BACKGROUND_STAR_COUNT 200

#define PROJECTILE_WIDTH 5.0f
#define PROJECTILE_HEIGHT 15.0f
#define MAX_PROJECTILES 20
#define FIRE_RATE_SECONDS 0.2f
#define PROJECTILE_SPEED 50.0f
#define PROJECTILE_DAMAGE 50.0f

// Waves
#define MAX_WAVES 10

#define MAX_ENEMIES 20
#define ENEMY_SPEED 10.0f
#define ENEMY_RESPAWN_TIME 0.5f

#endif